# Auto-generated. Maps emotion individual -> genre class (prefixed)
EMOTION_TO_GENRES = {
    "emo:confusion_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:curiosity_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:reflective_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:distressed_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:excitement_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:fear_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:grief_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:joy_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:love_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:sadness_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
    "emo:uplifting_1": ['emo:Action', 'emo:Biography', 'emo:Comedy', 'emo:ContextualGenre', 'emo:Crime', 'emo:Documentary', 'emo:Drama', 'emo:EmotionDrivenGenre', 'emo:Family', 'emo:Fantasy', 'emo:FormatGenre', 'emo:History', 'emo:Horror', 'emo:MovieGenre', 'emo:Musical', 'emo:Mystery', 'emo:NamedIndividual', 'emo:NarrativeGenre', 'emo:PsychologicalDrama', 'emo:Romance', 'emo:SciFi', 'emo:SpeculativeGenre', 'emo:Sport', 'emo:War'],
}
